/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USART3_IRQNO 39

int main(void)
{
    /*1- manually pend the pending bit for the USART3 IRQ number in NVIC
	this is normally done automatically but we do that here*/

	uint32_t *pISPR1 = (uint32_t *)0xE000E204; //address for ISPR1 register

	*pISPR1 |= (1<<(USART3_IRQNO % 32));

	//2- enable the USART3 IRQ number in NVIC

	uint32_t *pISER1 = (uint32_t *)0xE000E104; //address for ISER1 register

	*pISER1 |= (1<<(USART3_IRQNO % 32));

	for(;;);
}

//implement IRQHandle func
void USART3_IRQHandler(void)
{
	printf("USART IRQ_Handler called\n");
}














